# Generated by Django 4.0.4 on 2022-05-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinarnya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vinarnya.color'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vinarnya.country'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vinarnya.type'),
        ),
    ]
