# Generated by Django 4.0.4 on 2022-05-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinarnya', '0002_alter_wine_color_alter_wine_country_alter_wine_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='country',
            name='name_uk',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
