# Generated by Django 4.0.4 on 2022-05-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinarnya', '0003_rename_name_country_name_en_country_name_uk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='color',
            name='name_uk',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='type',
            name='name_uk',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
