# Generated by Django 4.0.4 on 2022-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinarnya', '0004_rename_name_color_name_en_rename_name_type_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.CharField(blank=True, default='Hello', max_length=50, null=True),
        ),
    ]
